Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

Load Cleaned Data

In [2]:
df = pd.read_csv("../data/processed/marketing_campaign_clean.csv")

df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,88,546,172,88,88,3,8,10,4,7,0,0,0,0,0,0,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,1,6,2,1,6,2,1,1,2,5,0,0,0,0,0,0,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,49,127,111,21,42,1,8,2,10,4,0,0,0,0,0,0,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,4,20,10,3,5,2,2,0,4,6,0,0,0,0,0,0,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,43,118,46,27,15,5,5,3,6,5,0,0,0,0,0,0,0

Customer Age

In [3]:
current_year = 2026

df["Age"] = current_year - df["Year_Birth"]

Customer Tenure (Days)

In [4]:
df["Dt_Customer"] = pd.to_datetime(df["Dt_Customer"])

df["Customer_Tenure"] = (
    pd.Timestamp("2026-01-01") - df["Dt_Customer"]
).dt.days

Family Size

In [5]:
df["Family_Size"] = df["Kidhome"] + df["Teenhome"] + 1

Total Spending

In [6]:
df["Total_Spending"] = (
    df["MntWines"] +
    df["MntFruits"] +
    df["MntMeatProducts"] +
    df["MntFishProducts"] +
    df["MntSweetProducts"] +
    df["MntGoldProds"]
)

Total Purchases

In [7]:
df["Total_Purchases"] = (
    df["NumWebPurchases"] +
    df["NumCatalogPurchases"] +
    df["NumStorePurchases"]
)

Total Accepted Campaigns

In [8]:
df["Accepted_Campaigns"] = (
    df["AcceptedCmp1"] +
    df["AcceptedCmp2"] +
    df["AcceptedCmp3"] +
    df["AcceptedCmp4"] +
    df["AcceptedCmp5"]
)

Total Children

In [9]:
df["Children"] = df["Kidhome"] + df["Teenhome"]

In [10]:
df[[
    "Age",
    "Customer_Tenure",
    "Family_Size",
    "Children",
    "Total_Spending",
    "Total_Purchases",
    "Accepted_Campaigns"
]].head()

,Age,Customer_Tenure,Family_Size,Children,Total_Spending,Total_Purchases,Accepted_Campaigns
0,69,4867,1,0,1617,22,0
1,72,4317,3,2,27,4,0
2,61,4516,1,0,776,20,0
3,42,4343,2,1,53,6,0
4,45,4365,2,1,422,14,0

Save Processed Dataset

In [11]:
df.to_csv("../data/processed/marketing_campaign_feature_engineered.csv", index=False)